### ISSUE TITLE
Needs to revert selinux workaround in commit 296c029

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_kernel_samsung_vivalto3gvn#6]
Needs to revert selinux workaround in commit 296c029

**Comment by diepquynh** [comment]
Why revert?

**Comment by ngoquang2708** [comment]
Need to set to permissive in Android part, not disable it like this. With this code, we cannot switch to enforce at all.

**Comment by ngoquang2708** [comment]
We need to find out what code in Android switch selinux to enforce and change it.

**Comment by diepquynh** [comment]
We need to add cm-12.1 kernel branch, since only CM12.1 needs Permissive only
You've modified the numbers only. Better have some "if" inside.

**Comment by ngoquang2708** [comment]
We can use this kernel for any cm version though, so just leave it as is
for now.

**Comment by diepquynh** [comment]
But... don't leave mali inside kernel. It causes graphics bugs in Gallery

**Comment by diepquynh** [comment]
I meant don't built-in it

**Comment by ngoquang2708** [comment]
It does. Maybe s/w codec used to create thumbnails in gallery cause  bugs.
Vào 11-02-2016 17:33, "Quyền" notifications@github.com đã viết:

**Comment by ngoquang2708** [comment]
Use logcat, you will see why gallery goes grey.

**Comment by diepquynh** [comment]
Btw, there's sth in this kernel make the phone freezes
I use original kernel from Sammy's source and it's gone.

**Comment by ngoquang2708** [comment]
I will do some test when I have fast internet connection.

**Comment by diepquynh** [comment]
Why don't you use MT3 instead?

**Comment by diepquynh** [comment]
Oops, MI3 :D

**Comment by ngoquang2708** [comment]
OK, I will try.

**Comment by ngoquang2708** [comment]
Playing Subway Surfers for 15 mins, still playing...

**Comment by diepquynh** [comment]
Reopen it

**Comment by diepquynh** [comment]
If not then seems my source is very dirty tho

**Comment by ngoquang2708** [comment]
Still playing, tethering using bluetooth to use internet through it...

**Comment by diepquynh** [comment]
Right. That means my source is very dirty LOL

**Comment by ngoquang2708** [comment]
Clean build for now :)

**Comment by koquantam** [comment]
Dude, do you have any ideas for this?
`a1@desktop:~/cm-11.0/kernel/custom/vivalto3gvn$ make
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[1]: `include/generated/mach-types.h' is up to date.
  CALL    scripts/checksyscalls.sh
  CC      scripts/mod/devicetable-offsets.s
  GEN     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/file2alias.o
  HOSTLD  scripts/mod/modpost
  CHK     include/generated/compile.h
  CC      block/blk-core.o
block/blk-core.c: In function 'blk_pm_put_request':
block/blk-core.c:1332:2: warning: left shift count >= width of type [enabled by default]
block/blk-core.c: In function 'blk_pm_peek_request':
block/blk-core.c:2139:6: warning: left shift count >= width of type [enabled by default]
block/blk-core.c: In function 'blk_dev_init':
block/blk-core.c:3254:2: error: call to '__compiletime_assert_3255' declared with attribute error: BUILD_BUG_ON failed: __REQ_NR_BITS > 8 * sizeof(((struct request *)0)->cmd_flags)
make[1]: *** [block/blk-core.o] Error 1
make: *** [block] Error 2
`

**Comment by ngoquang2708** [comment]
I have no idea.

**Comment by ngoquang2708** [comment]
Reverted.

**Comment by diepquynh** [comment]
@ngoquang2708 
Bro, do you need upgrading kernel? I have a squashed commit from 3.10.18 to 3.10.102

**Comment by ngoquang2708** [comment]
What is it? A bunch of commits?

**Comment by diepquynh** [comment]
Yes it is. In theory, a squashed commit is a commit which is a combination of all commits into one single commit

**Comment by diepquynh** [comment]
I have merged all of the patches from .18 to .102, so you don't have to use patch -p1 for 85 times
If you need it, I'll upload it

**Comment by ngoquang2708** [comment]
I thought that it would be a list of commits, not a single commit. It would
be big :) OK, upload it for me.

**Comment by diepquynh** [comment]
@ngoquang2708 
Bro, please read this line in system/core/init/init.cpp: https://github.com/ngoquang2708/android_system_core/blob/cm-13.0/init/init.cpp#L802

This means we can use "androidboot." params in kernel cmdline right?

**Comment by ngoquang2708** [comment]
I do not think my board can change cmdline. I do not think your board can
do that neither.

**Comment by diepquynh** [comment]
I think we can with this: https://github.com/FireLord1/android_kernel_samsung_smdk5260/commit/3a44e19140e690158ef9108a588150596f001e0d

**Comment by ngoquang2708** [comment]
That is nice!

**Comment by ngoquang2708** [comment]
But what would you like to do with it?

**Comment by diepquynh** [comment]
You know, we have to make our source AOSP friendly (means without patches)

**Comment by diepquynh** [comment]
So CM will take our trees :)

**Comment by ngoquang2708** [comment]
How could it possible without patches?

**Comment by diepquynh** [comment]
You know, no SoCs are the best without first stage patches
So, I guess we have to make our own at gerrit

**Comment by ngoquang2708** [comment]
It will take much much time and effort.

**Comment by diepquynh** [comment]
I just planning to do it
